### PR TITLE
Changes to support using the Nonce, refunds, and transaction lists

### PR DESCRIPTION
**Pull request by skurvish**

### CODE REVIEW

**Comment by skurvish** [comment]
Please run checks again. I have modified to conform to PSR2. I think I have them all.

**Comment by skurvish** [comment]
I am going to continue testing this offline. The test that is failing is one I did not write, MikeyBeck wrote it and there seems to be a class missing. I will fix it offline and then push the changes when it is all working.

**Comment by skurvish** [comment]
Yeah! That was a lot more work than I expected.

**Comment by gl3nda85** [comment]
why hasn't this been merged?

**Pull request merged**
